spring:
  docker:
    compose:
      lifecycle-management: start-and-stop
  datasource:
    url: jdbc:mysql://localhost:3307/aspirefitness
    username: arne
    password: slot
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    generate-ddl: true
    show-sql: true

server:
  port: 8080
